<?php

namespace backend\controllers;

use common\helpers\Encrypt;
use Yii;
use frontend\models\FormPhoto;
use frontend\models\FormCollege;
use frontend\models\search\FormPhotoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PhotoController implements the CRUD actions for FormPhoto model.
 */
class PhotoController extends Controller
{
    public $college;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function beforeAction($action)
    {
        $colleges = new FormCollege();

        $datas = $colleges->find()->all();

        foreach ($datas as $k => $data) {
            $tmpCollege = $data->toArray();
            $this->college[$tmpCollege['id']] = $tmpCollege['name'];
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all FormPhoto models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FormPhotoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'college'=>$this->college
        ]);
    }
    public function actionPass($id)
    {
        $searchModel = new FormPhotoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $model = $this->findModel($id);
        if (!empty($model)) {
            $model->status = 1;
            $model->save();
        }
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'college'=>$this->college
        ]);
    }
    /**
     * Displays a single FormPhoto model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'college'=>$this->college
        ]);
    }

    /**
     * Creates a new FormPhoto model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new FormPhoto();
        $postData = Yii::$app->request->post();
        if(Yii::$app->request->isPost) {
            $photo = $postData['FormPhoto']['photo'];
            $photo = json_decode($photo, true);
            $photo = \common\helpers\Encrypt::array2string($photo);
            $postData['FormPhoto']['photo']=$photo;

        }
        if ($model->load($postData) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'college'=>$this->college
            ]);
        }
    }

    /**
     * Updates an existing FormPhoto model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $postData = Yii::$app->request->post();
        if(Yii::$app->request->isPost) {
            $photo = $postData['FormPhoto']['photo'];
            $photo = json_decode($photo, true);
            $photo = \common\helpers\Encrypt::array2string($photo);
            $postData['FormPhoto']['photo']=$photo;

        }
        if ($model->load($postData) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'college'=>$this->college
            ]);
        }
    }

    /**
     * Deletes an existing FormPhoto model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the FormPhoto model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return FormPhoto the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = FormPhoto::findOne($id)) !== null) {
            if(!empty($model->photo)){
                $photo=\common\helpers\Encrypt::string2array($model->photo);
                $model->photo=stripslashes(json_encode($photo));
//                $model->photo=json_encode(\common\helpers\Encrypt::string2array($model->photo));
            }
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
