<?php


namespace frontend\controllers\api;

use Yii;
use frontend\models\Content;
use yii\filters\AccessControl;
use frontend\models\Search\ContentSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrganController implements the CRUD actions for Organ model.
 */
class ActivationController extends CurdController
{
    public $enableCsrfValidation = false;//关闭csrf验证
    public $searchField=[
        'title'  , 'catid' , 'keywords'  , 'description', 'username','content'
        //'videoPath', 'content', 'status'
    ];
	public $orderField=['activid'];
    public $modelName="Activation";
    public $searchModelName="ActivationSearch";
    public $namespace="\\backend\\models\\";
    public $action=['list','logs'];//允许的操作
    public $returnField=['*'];
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'rules' => [
//                    [
//                        'actions' => ['list','view'],
//                        'allow' => true,
//                    ],
//                ],
//            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function  init(){
        parent::init();
        $this->guestQuit();
        // $this->getUid();
    }
    public function actionLogs(){
//        $queryParams['m_userid']=Yii::$app->user->id;
//        $order['activid']="asc";
//        $this->queryParams['params']=json_encode($queryParams);
//        $this->queryParams['order']=json_encode($order);
        $this->searchModelName="ActivationlogSearch";
        $queryParams['userid']=Yii::$app->user->id;
        $this->queryParams['params']=json_encode($queryParams);
        $this->getUid();
        parent::_list($this->searchModelName, $this->orderField, $this->searchField, $this->namespace); // TODO: Change the autogenerated stub
    }
    public function _list($SearchModel, $orderField, $searchField, $namespace = "\\frontend\\models\\")
    {
        $queryParams['m_userid']=Yii::$app->user->id;
        $order['activid']="asc";
        $this->queryParams['params']=json_encode($queryParams);
        $this->queryParams['order']=json_encode($order);
        parent::_list($SearchModel, $orderField, $searchField, $namespace); // TODO: Change the autogenerated stub
    }
    /**
     * Finds the Content model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Content the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
//    protected function findContent($id)
//    {
//        return $this->findModel($id,true,"Content","\\backend\\models");
//    }
}