<?php


namespace frontend\controllers\api;

use frontend\models\FormAddress;
use Yii;
use frontend\models\Content;
use yii\filters\AccessControl;
use frontend\models\Search\ContentSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrganController implements the CRUD actions for Organ model.
 */
class AddressController extends CurdController
{
    public $enableCsrfValidation = false;//关闭csrf验证
    public $orderField=[
        'id'  , 'userid' , 'order'  , 'inputtime', 'updatetime',
        //'videoPath', 'content', 'status'
    ];
    public $searchField=[
        'title'  , 'catid' , 'keywords'  , 'description', 'username','content','linkage'
        //'videoPath', 'content', 'status'
    ];
    public $modelName="FormAddress";
    public $searchModelName="FormAddressSearch";
    public $namespace="\\frontend\\models\\";
    public $action=['list',"view",'create','update','delete','setdefault'];//允许的操作
    public $returnField=['*'];
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'rules' => [
//                    [
//                        'actions' => ['list','view'],
//                        'allow' => true,
//                    ],
//                ],
//            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function  init(){
        parent::init();
        $this->guestQuit();
        $this->getUid();
    }
    //默认地址
    public function actionSetdefault(){
        $this->rawBody[$this->modelName]['status']=3;
        $address = FormAddress::findOne(["status"=>3]);
        if($address){
            $address->status=2;
            $address->save();
        }
        parent::_update($this->modelName, $this->namespace); // TODO: Change the autogenerated stub
    }

    public function _list($SearchModel, $orderField, $searchField, $namespace = "\\frontend\\models\\")
    {
        $queryParams['userid']=Yii::$app->user->id;
        $this->queryParams['params']=json_encode($queryParams);
        parent::_list($SearchModel, $orderField, $searchField, $namespace); // TODO: Change the autogenerated stub
    }
    public function _View($model, $namespace = "\\frontend\\models\\", $checkUserNot = true)
    {
        parent::_View($model, $namespace,false); // TODO: Change the autogenerated stub
    }
    /**
     * Finds the Content model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Content the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
//    protected function findContent($id)
//    {
//        return $this->findModel($id,true,"Content","\\backend\\models");
//    }
}