<?php
namespace frontend\controllers\api;

use Yii;
use yii\filters\VerbFilter;
use common\models\Order;


class ServiceController extends ApiController
{
    public $wanjieurl;
    public $desktopurl;
    public $client;
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['POST', 'GET'],
                ],
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->wanjieurl = yii::$app->params["api"]["vboss"]."/hqy/addWangjieFromCollege";
        $this->desktopurl = yii::$app->params["api"]["vboss"]."/hqy/addDesktopFromCollege";
        $this->client = new Client([
            'transport' => 'yii\httpclient\CurlTransport'
        ]);
    }

    public function actionSet(){
        $data = json_decode(Yii::$app->request->rawBody, true);
        if(empty($data['trade_sn'])){
            $this->setReturn("0003", "failed", "", "trade_sn参数错误");
        }
        $orderinfo = Order::arrayOne(['trade_sn' => $data['trade_sn']]);//获取商品详情
        foreach($orderinfo['goods'] as $key=>$val){
            if($val['type']==1){
                $this->_setCourse($orderinfo,$val);
            }elseif($val['type']==2){
                $this->_setLab($orderinfo,$val);
            }elseif($val['type']==3){
                $this->_setPractical($orderinfo,$val);
            }
        }
    }
    /*
     *课程授权接口
     * */
    public function _setCourse($orderinfo,$val){
        $myCourse = new Mycourse();
        $Course = new Course();
        $courseInfo = $Course::find()
            ->where(['course_id' => $val['association_id']])
            ->one();
        $myCourse->courseid = $courseInfo['course_id'];
        $myCourse->userid = $val['userid'];
        $myCourse->auth_start_at = time();
        $myCourse->auth_end_at = time()+$courseInfo['auth_count_time'];
        $isGrant = $myCourse->save();
        if($isGrant){
            $this->setReturn("0000","success");
        }

    }
    /***
     *实验室授权接口
     *     */
    public function _setLab($orderinfo,$val){
        $lab = new Lab();
        $labinfo = $lab::find()->where(['labid'=>$val['association_id']])->one();//查询实验室
        if($labinfo["type"]=="desktop"){//桌面授权
            $parArr = [
                'trade_sn'=>0,
                'loginname'=>$orderinfo['username'],
                'classid'=>0,
                'order_source'=>'college',
                'begin_time'=>time(),
                'end_time'=>time()+123000,
                'can_use_second'=>123200,
                'order_type'=>11,
                'lab_code'=>$val['lab_code']
            ];
            $response = $this->client->createRequest()
                ->setMethod('json')
                ->setUrl(  $this->desktopurl)
                ->setData($parArr)
                ->send();
            if($response->isOk){
                if($response->data['code']==0){
                    //生成授权码

                }
            }
        }elseif($labinfo["type"]=="wanjie"){//网界授权
           $attribute = array();
           if($val['attrs_info']){
               foreach($val['attrs_info'] as $k=>$v){
                   if($val['attrtype']=="time"){
                       $attribute[$k]['duration_days'] = $v['key'];
                   }elseif($val['attrtype']=="module"){
                       $attribute[$k]['attr_code'] = $v['key'];
                       $attribute[$k]['attr_name'] = $v['name'];
                   }
               }
           }
            $parArr = [
                'trade_sn'=>0,
                'loginname'=>$orderinfo['username'],
                'user_name'=>$orderinfo['username'],
                'lab_code'=>$val['lab_code'],
                'attribute'=>$attribute
            ];
            $response = $this->client->createRequest()
                ->setMethod('json')
                ->setUrl(  $this->desktopurl)
                ->setData($parArr)
                ->send();
            if($response->isOk){
                if($response->data['code']==0){
                    //生成授权码
                }
            }
        }

    }
    /*
     * 实训授权接口
     * */
    public function _setPractical($orderinfo,$val){
        $practical = new Practical();
        $practicalinfo = $practical::find()->where(['practicalid'=>$val['association_id']])->one();//查询实验室
        if($practicalinfo["type"]=="desktop"){//桌面授权
            $parArr = [
                'trade_sn'=>0,
                'loginname'=>$orderinfo['username'],
                'classid'=>0,
                'order_source'=>'college',
                'begin_time'=>time(),
                'end_time'=>time()+123000,
                'can_use_second'=>123200,
                'order_type'=>11,
                'lab_code'=>$val['lab_code']
            ];
            $response = $this->client->createRequest()
                ->setMethod('json')
                ->setUrl(  $this->desktopurl)
                ->setData($parArr)
                ->send();
            if($response->isOk){
                if($response->data['code']==0){
                    //生成授权码

                }
            }
        }elseif($practicalinfo["type"]=="wanjie"){//网界授权
            $attribute = array();
            if($val['attrs_info']){
                foreach($val['attrs_info'] as $k=>$v){
                    if($val['attrtype']=="time"){
                        $attribute[$k]['duration_days'] = $v['key'];
                    }elseif($val['attrtype']=="module"){
                        $attribute[$k]['attr_code'] = $v['key'];
                        $attribute[$k]['attr_name'] = $v['name'];
                    }
                }
            }
            $parArr = [
                'trade_sn'=>0,
                'loginname'=>$orderinfo['username'],
                'user_name'=>$orderinfo['username'],
                'lab_code'=>$val['lab_code'],
                'attribute'=>$attribute
            ];
            $response = $this->client->createRequest()
                ->setMethod('json')
                ->setUrl(  $this->desktopurl)
                ->setData($parArr)
                ->send();
            if($response->isOk){
                if($response->data['code']==0){
                    //生成授权码
                }
            }
        }

    }
    /*
     * 直播授权接口
     * **/
    public function _setLive($orderinfo){

    }
}
