<?php


namespace frontend\controllers\api;

use Yii;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\UsePractical;
use common\models\MyPractical;
use common\models\Goods;
use common\models\Practical;

/**
 * OrganController implements the CRUD actions for Organ model.
 */
class UsePracticalController extends CurdController
{
    public $enableCsrfValidation = false;//关闭csrf验证
    public $orderField=[
        'id'  , 'userid' , 'order'  , 'inputtime', 'updatetime',
        //'videoPath', 'content', 'status'
    ];
    public $searchField=[
        'title'  , 'catid' , 'keywords'  , 'description', 'username','content'
        //'videoPath', 'content', 'status'
    ];
    public $modelName="UsePractical";
    public $searchModelName="UsePracticalSearch";
    public $namespace="\\frontend\\models\\";
    public $action=['list',"view",'create','update','delete'];//允许的操作
    public $returnField=['*'];
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'rules' => [
//                    [
//                        'actions' => ['list','view'],
//                        'allow' => true,
//                    ],
//                ],
//            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function  init(){
        parent::init();
       // $this->guestQuit();
        $this->getUid();
    }
    public function _list()
    {
        $UsePractical = new UsePractical();
        $params = json_decode(yii::$app->request->rawBody,true);
        //$params['userid']=Yii::$app->user->id;

        $list = $UsePractical::find()->where("userid = ".Yii::$app->user->id." and status>0")->asArray()->all();
        $lablist = array();
        //
        $mypractical = new MyPractical();
        foreach($list as $key=>$val){
            $myprainfo = $mypractical::find()
                ->where(['practical_id'=>$val['practical_id']])
                ->one();
            $pralist[$key]['practical_id'] = $myprainfo['practical_id'];
            $pralist[$key]['practical_name'] = $myprainfo['practical_name'];
            $pralist[$key]['begin_time'] = $myprainfo['begin_time'];
            $pralist[$key]['end_time'] = $myprainfo['end_time'];
            $goods = new goods();
            $goodsinfo = $goods::find()
                ->where(['goods_id'=>$myprainfo['goods_id']])
                ->asArray()
                ->one();
            $pralist[$key]['goods_thumb'] = $goodsinfo['goods_thumb'];
            $practical = new Practical();
            $prainfo =  $practical::find()
                ->where(['practicalid'=>$goodsinfo['association_id']])
                ->asArray()
                ->one();

           // var_dump($prainfo);
            if($prainfo['type']=="desktop"){
                $pralist[$key]['practical_url'] = \common\helpers\Encrypt::yungongchang(['use_url'=>yii::$app->params['api']['ygc']],Yii::$app->user->identity);
            }else{
                $pralist[$key]['practical_url'] = $myprainfo['practical_url'];
            }
        }
        $this->setReturn('0000', 'success', $pralist);
        //parent::_list($SearchModel, $orderField, $searchField, $namespace); // TODO: Change the autogenerated stub
    }
    public function _View($model, $namespace = "\\common\\models\\", $checkUserNot = true)
    {
        parent::_View($model, $namespace,false); // TODO: Change the autogenerated stub
    }
    /**
     * Finds the Content model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Content the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
//    protected function findContent($id)
//    {
//        return $this->findModel($id,true,"Content","\\backend\\models");
//    }
}