<?php
/**
 * User: yeshulin
 * Date: 2016/7/29
 * Time: 14:29
 */

namespace frontend\controllers;

use common\helpers\SEO;
use Yii;
use yii\web\Controller;

class WebController extends Controller
{

    protected $apicollege;

    public function init()
    {
        $this->apicollege = Yii::$app->params['api']['college'];

    }
    public function beforeAction($action)
    {
//        var_dump(Yii::$app->requestedAction->controller->action);
        $route = Yii::$app->requestedRoute;
        $title = Yii::$app->params['routeTile'][$route];
        if(!preg_match("/site\/[index|site]/",$route)) SEO::setSEO($title);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function showmessage($msg, $url, $status = 'error')
    {
        return $this->render("//layouts/message", ['msg' => $msg, 'url' => $url, 'status' => $status]);
    }

}
