<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%mycourse}}".
 *
 * @property integer $courseid
 * @property integer $userid
 * @property integer $auth_start_at
 * @property integer $auth_end_at
 */
class Mycourse extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%mycourse}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['courseid', 'userid', 'auth_start_at'], 'required'],
            [['courseid', 'userid', 'auth_start_at', 'auth_end_at'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'courseid' => '课程ID',
            'userid' => '用户ID',
            'auth_start_at' => '认证开始时间',
            'auth_end_at' => '认证结束时间',
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if ($this->getIsNewRecord())
        {
            $this->auth_start_at = time();
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }




    public function getCourse()
    {
        return $this->hasOne(Course::className(), ['course_id'=> 'courseid'])->asArray(true);
    }
}
