<?php
/**
 * Created by PhpStorm.
 * User: IUOD
 * Date: 2016/7/25
 * Time: 14:42
 */

namespace backend\models;
use common\models\Goods as ComGoods;
use yii\web\UploadedFile;
use Yii;

class Goods extends ComGoods
{
    public $create_at_start;
    public $create_at_end;


    public function save($runValidation = true, $attributeNames = null)
    {
        if (!$this->order)
        {
            $this->order = 0;
        }
        if (!$this->price) {
            $this->price = 0;
        }
        if (!$this->selltype) {
            $this->selltype = 0;
        }

        if (!$this->minbuynumber)
        {
            $this->minbuynumber = 1;
        }
        $this->_setAssociationStatus($this->status, $this->association_id, $this->type);

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    private function _setAssociationStatus($status, $association_id, $type)
    {
        $model = null;
        switch ($type)
        {
            case self::TYPE_COURSE:
                $model = Course::findOne($association_id);
                break;

            case self::TYPE_LAB:
                $model = Course::findOne($association_id);
                break;

            case self::TYPE_LIVE:
                $model = Course::findOne($association_id);
                break;

            case self::TYPE_PRACTICAL:
                $model = Course::findOne($association_id);
                break;

            case self::TYPE_ZYRZ:
                $model = Course::findOne($association_id);
                break;
        }
        if ($model == null)
        {
            return false;
        }

        if ($status == self::STATUS_DEFAULT)
        {
            $model->status = Course::STATUS_DEFAULT;
        } else {
            $model->status = Course::STATUS_DELETE;
        }
        $model->save();
    }


    public static function setDataSync($syncData, $association_id, $type)
    {
        if (empty($syncData))
        {
            return false;
        }
        $model = self::find()->where(['association_id'=> $association_id, 'type'=>$type])->one();
        $model->load($syncData, '');
        $model->save();
    }

}