<?php
/**
 * Created by PhpStorm.
 * User: IUOD
 * Date: 2016/8/1
 * Time: 17:09
 */

namespace backend\models;

use common\models\Lab as ComLab;

class Lab extends ComLab
{
    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}