<?php
/**
 * Created by PhpStorm.
 * User: IUOD
 * Date: 2016/7/27
 * Time: 14:00
 */

namespace backend\models;

use common\models\Video as ComVideo;
class Video extends ComVideo
{
    public function save($runValidation = true, $attributeNames = null)
    {
        $this->update_at = time();
        $this->status = self::STATUS_DEFAULT;
        $this->userid = \Yii::$app->user->id;
        $this->usertype = 99;
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}