<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%myxuecourse}}".
 *
 * @property integer $userid
 * @property integer $courseid
 * @property integer $sectionid
 * @property integer $barsid
 * @property integer $knowsid
 * @property integer $create_at
 */
class Myxuecourse extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%myxuecourse}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userid', 'courseid', 'sectionid', 'barsid', 'knowsid', 'create_at'], 'required'],
            [['userid', 'courseid', 'sectionid', 'barsid', 'knowsid', 'create_at'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'userid' => '用户ID',
            'courseid' => '课程ID',
            'sectionid' => '章节ID',
            'barsid' => '小节ID',
            'knowsid' => '知识点ID',
            'create_at' => '创建时间',
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if ($this->getIsNewRecord())
        {
            $this->create_at = time();
            $this->userid = Yii::$app->user->id;
            return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
        }
        return false;
    }
}
