<?php
/**
 * Created by PhpStorm.
 * User: IUOD
 * Date: 2016/7/29
 * Time: 16:00
 */

namespace frontend\models;

use Yii;
use common\models\Video as ComVideo;

class Video extends ComVideo
{
    public $pagesize;

    public $page;

    public function search($params)
    {
        $this->pagesize = isset($params['pagesize']) ? intval($params['pagesize']) : 10;
        $this->page = isset($params['page']) ? intval($params['page']) : 1;

        $query = self::find()->where(['userid'=>Yii::$app->user->id]);

        $totalCount = $query->count();
        $this->page = $this->page > 0 ? $this->page : 1;
        $this->pagesize = $this->pagesize > 0 ? $this->pagesize : 1;
        $pages = ceil($totalCount/$this->pagesize);
        if ($this->page > $pages) {
            $this->page = $pages;
        }
        return [
            'data'=>$query->offset(($this->page -1) * $this->pagesize)->limit($this->pagesize)->asArray(true)->all(),
            'total'=>$totalCount,
            'currentPage'=>$this->page,
            'pageSize'=>$this->pagesize
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $this->userid = Yii::$app->user->id;
        $this->usertype = Yii::$app->user->identity->usertype;
        $this->update_at = time();
        if (!$this->create_at) {
            $this->create_at = time();
        }
        $this->status = self::STATUS_CHECK;
        $this->type = self::TYPE_COURSE;
        if (!$this->validate())
        {
            return false;
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}